"""add foreign key constraints

Revision ID: ec1673bcefc3
Revises: 6d27a51e02d6
Create Date: 2025-11-10 14:22:26.344750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec1673bcefc3"
down_revision: Union[str, Sequence[str], None] = "6d27a51e02d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "approval_requests", "workflow_executions", ["execution_id"], ["id"]
    )
    op.create_index(
        op.f("ix_rollback_actions_status"), "rollback_actions", ["status"], unique=False
    )
    op.create_foreign_key(None, "rollback_actions", "workflow_executions", ["execution_id"], ["id"])
    op.create_foreign_key(None, "state_snapshots", "workflow_executions", ["execution_id"], ["id"])
    op.create_foreign_key(None, "step_executions", "workflow_executions", ["execution_id"], ["id"])
    op.drop_index(op.f("ix_workflow_name"), table_name="workflow_definitions")
    op.create_index(
        op.f("ix_workflow_definitions_name"), "workflow_definitions", ["name"], unique=False
    )
    op.create_foreign_key(
        None, "workflow_executions", "workflow_definitions", ["workflow_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow_executions", type_="foreignkey")
    op.drop_index(op.f("ix_workflow_definitions_name"), table_name="workflow_definitions")
    op.create_index(op.f("ix_workflow_name"), "workflow_definitions", ["name"], unique=False)
    op.drop_constraint(None, "step_executions", type_="foreignkey")
    op.drop_constraint(None, "state_snapshots", type_="foreignkey")
    op.drop_constraint(None, "rollback_actions", type_="foreignkey")
    op.drop_index(op.f("ix_rollback_actions_status"), table_name="rollback_actions")
    op.drop_constraint(None, "approval_requests", type_="foreignkey")
    # ### end Alembic commands ###
